import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintPluginAstro from 'eslint-plugin-astro';

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  {
    languageOptions: {
      globals: {
        document: 'readonly',
        window: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        HTMLElement: 'readonly',
        Event: 'readonly',
        matchMedia: 'readonly',
        performance: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        MutationObserver: 'readonly',
        NodeList: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLStyleElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLFormElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        history: 'readonly',
        location: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        navigator: 'readonly',
        getComputedStyle: 'readonly',
        addEventListener: 'readonly',
        removeEventListener: 'readonly',
        // p5.js 全局变量
        createCanvas: 'readonly',
        background: 'readonly',
        fill: 'readonly',
        noFill: 'readonly',
        stroke: 'readonly',
        noStroke: 'readonly',
        strokeWeight: 'readonly',
        ellipse: 'readonly',
        rect: 'readonly',
        line: 'readonly',
        beginShape: 'readonly',
        endShape: 'readonly',
        vertex: 'readonly',
        push: 'readonly',
        pop: 'readonly',
        translate: 'readonly',
        rotate: 'readonly',
        random: 'readonly',
        randomSeed: 'readonly',
        noise: 'readonly',
        noiseSeed: 'readonly',
        sin: 'readonly',
        cos: 'readonly',
        tan: 'readonly',
        atan2: 'readonly',
        sqrt: 'readonly',
        abs: 'readonly',
        map: 'readonly',
        lerpColor: 'readonly',
        floor: 'readonly',
        frameCount: 'readonly',
        TWO_PI: 'readonly',
        PI: 'readonly',
        HALF_PI: 'readonly',
        QUARTER_PI: 'readonly',
        CLOSE: 'readonly',
        color: 'readonly',
        millis: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      'no-case-declarations': 'off',
    },
  },
  {
    ignores: [
      'dist/',
      '.astro/',
      'node_modules/',
      'playwright-report/',
      'public/service-worker.js',
    ],
  },
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        process: 'readonly',
      },
    },
  },
];
