/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--qi-brand-emerald)',
        secondary: 'var(--qi-text-secondary)',
        success: 'var(--qi-emerald-500)',
        danger: '#dc3545',
        warning: 'var(--qi-brand-amber)',
        info: 'var(--qi-brand-mint)',
        light: 'var(--qi-bg-base)',
        dark: 'var(--qi-surface-main)',
        text: {
          primary: 'var(--qi-text-primary)',
          secondary: 'var(--qi-text-secondary)',
          muted: 'var(--qi-text-muted)',
          inverse: 'var(--qi-text-inverse)',
        },
        bg: {
          base: 'var(--qi-bg-base)',
          surface: 'var(--qi-surface-main)',
          sub: 'var(--qi-surface-sub)',
        },
        border: {
          default: 'var(--qi-border-default)',
          subtle: 'var(--qi-border-subtle)',
          strong: 'var(--qi-border-strong)',
        },
        emerald: {
          50: 'var(--qi-emerald-50)',
          100: 'var(--qi-emerald-100)',
          200: 'var(--qi-emerald-200)',
          300: 'var(--qi-emerald-300)',
          400: 'var(--qi-emerald-400)',
          500: 'var(--qi-emerald-500)',
          600: 'var(--qi-emerald-600)',
          700: 'var(--qi-emerald-700)',
          800: 'var(--qi-emerald-800)',
          900: 'var(--qi-emerald-900)',
        },
        amber: {
          50: 'var(--qi-amber-50)',
          100: 'var(--qi-amber-100)',
          200: 'var(--qi-amber-200)',
          300: 'var(--qi-amber-300)',
          400: 'var(--qi-amber-400)',
          500: 'var(--qi-amber-500)',
          600: 'var(--qi-amber-600)',
          700: 'var(--qi-amber-700)',
          800: 'var(--qi-amber-800)',
          900: 'var(--qi-amber-900)',
        },
        mint: {
          50: 'var(--qi-mint-50)',
          100: 'var(--qi-mint-100)',
          200: 'var(--qi-mint-200)',
          300: 'var(--qi-mint-300)',
          400: 'var(--qi-mint-400)',
          500: 'var(--qi-mint-500)',
          600: 'var(--qi-mint-600)',
          700: 'var(--qi-mint-700)',
          800: 'var(--qi-mint-800)',
          900: 'var(--qi-mint-900)',
        },
      },
      fontFamily: {
        sans: ['var(--qi-font-sans)'],
        serif: ['var(--qi-font-serif)'],
        mono: ['var(--qi-font-mono)'],
      },
      spacing: {
        xs: 'var(--qi-space-xs)',
        sm: 'var(--qi-space-sm)',
        md: 'var(--qi-space-md)',
        lg: 'var(--qi-space-lg)',
        xl: 'var(--qi-space-xl)',
        '2xl': 'var(--qi-space-2xl)',
        '3xl': 'var(--qi-space-3xl)',
        '4xl': 'var(--qi-space-4xl)',
        '5xl': 'var(--qi-space-5xl)',
        '6xl': 'var(--qi-space-6xl)',
        '7xl': 'var(--qi-space-7xl)',
        '8xl': 'var(--qi-space-8xl)',
        '9xl': 'var(--qi-space-9xl)',
      },
      borderRadius: {
        sm: 'var(--qi-radius-sm)',
        md: 'var(--qi-radius-md)',
        lg: 'var(--qi-radius-lg)',
        xl: 'var(--qi-radius-xl)',
        full: 'var(--qi-radius-full)',
        card: 'var(--qi-radius-card)',
        button: 'var(--qi-radius-button)',
      },
      boxShadow: {
        sm: 'var(--qi-shadow-sm)',
        DEFAULT: 'var(--qi-shadow)',
        md: 'var(--qi-shadow-md)',
        lg: 'var(--qi-shadow-lg)',
        xl: 'var(--qi-shadow-xl)',
        hover: 'var(--qi-shadow-hover)',
      },
      zIndex: {
        base: 'var(--qi-z-base)',
        content: 'var(--qi-z-content)',
        nav: 'var(--qi-z-nav)',
        overlay: 'var(--qi-z-overlay)',
        noise: 'var(--qi-z-noise)',
        'back-top': 'var(--qi-z-back-top)',
        'skip-link': 'var(--qi-z-skip-link)',
        progress: 'var(--qi-z-progress)',
      },
      fontSize: {
        xs: 'var(--qi-text-xs)',
        sm: 'var(--qi-text-sm)',
        base: 'var(--qi-text-base)',
        lg: 'var(--qi-text-lg)',
        xl: 'var(--qi-text-xl)',
        '2xl': 'var(--qi-text-2xl)',
        '3xl': 'var(--qi-text-3xl)',
        '4xl': 'var(--qi-text-4xl)',
        '5xl': 'var(--qi-text-5xl)',
        '6xl': 'var(--qi-text-6xl)',
        '7xl': 'var(--qi-text-7xl)',
      },
      transitionProperty: {
        DEFAULT: 'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
      },
      transitionTimingFunction: {
        DEFAULT: 'ease',
        'spring': 'var(--qi-spring)',
        'spring-soft': 'var(--qi-spring-soft)',
        'spring-snappy': 'var(--qi-spring-snappy)',
      },
      transitionDuration: {
        DEFAULT: 'var(--qi-transition-base)',
        'fast': 'var(--qi-transition-fast)',
        'normal': 'var(--qi-transition)',
      },
    },
  },
  plugins: [],
}